<div style="font-size: 27px; color: red; text-align: center; font-weight: bold;"> 
Probability and Bayes Theorem (Questions) </div>

<div style="font-size: 25px; color: red; text-align: center; font-weight: bold;"> 
Part 1: Probability </div>

Load the Dataset and Answer the Following Questions:
1. What is the Probability that the Customer has a Credit Card ?

2. What is the Probability that the Customer age is greater than 50 ?
3. What is the Probability that the Customer is illiterate ?
4. What is the Probability that the Customer has a Telephone ?
5. What is the Probability that the Customer is Single and has a Credit Card ?
6. What is the Probability that the Customer is Male and has at most 6 Year of Education ?
7. What is the Probability that the Customer is Retired and is divorced ?
8. Given the Customer has the credit card, find the probability that he/she is married
9. If a customer has a blue collar job, find the probability that he has a housing

Import necessary libraries, load the 'credit_card.csv' dataset, display a data sample, determine dataset dimensions, and determine the summary statistics for quantitative and qualtitative columns.

In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
warnings.filterwarnings('ignore')

In [115]:
df = pd.read_csv('credit_card.csv')
print(df.shape)
print(df.head())

(41188, 10)
   gender  age        job  marital    education default housing loan  \
0  female   56  housemaid  married     basic.4y      no      no   no
1    male   57   services  married  high.school     yes      no   no
2  female   37   services  married  high.school      no     yes   no
3  female   40     admin.  married     basic.6y      no      no   no
4  female   56   services  married  high.school      no      no  yes

     contact CreditCard
0  telephone         no
1  telephone         no
2  telephone         no
3  telephone         no
4  telephone         no

In [116]:
df.describe(include=['object', 'category'])

,gender,job,marital,education,default,housing,loan,contact,CreditCard
count,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,2,12,4,8,2,2,2,2,2
top,female,admin.,married,university.degree,no,yes,no,cellular,no
freq,20798,10422,24928,12168,32588,22566,33950,26144,36548

In [117]:
df.columns

Index(['gender', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'CreditCard'],
      dtype='object')

## Q1: What is the Probability that the Customer has a Credit Card ?

In [118]:
# df['CreditCard'].value_counts()
print((df['CreditCard'] == "yes").sum() / len(df['CreditCard']))
print((df['CreditCard'] == 'yes').mean())

0.11265417111780131
0.11265417111780131

It has 11% probability

## Q2: What is the Probability that the Customer age is greater than 50 ?

In [119]:
(df['age'] > 50).mean()

np.float64(0.17432261823832185)

17% probability that Customer age > 50

## Q3: What is the probability that the customer is illiterate?

In [120]:
(df['education'] == 'illiterate').mean() # 0.0437%

np.float64(0.0004370204914052637)

## Q4: What is the Probability that the Customer has a Telephone ?

In [121]:
(df.contact == 'telephone').mean()

np.float64(0.3652520151500437)

## Q5: What is the Probability that the Customer is Single and has a Credit Card ?

In [122]:
((df['marital'] == 'single') & (df['CreditCard'] == 'yes')).mean()

np.float64(0.03933184422647373)

## Q6: What is the Probability that the Customer is Male and has at most 6 Year of Education ?

In [123]:
((df['gender'] == 'male')&(df['education'].isin(['basic.4y', 'basic.6y', 'illiterate']))).mean()

np.float64(0.0778382053025153)

## Q7: What is the Probability that the Customer is Retired and is divorced ?

In [124]:
((df.job == 'retired') & (df.marital == 'divorced')).mean()

np.float64(0.008449062833835098)

## Q8: Given the Customer has the credit card, find the probability that he/she is married ?

In [125]:
Pa = df['CreditCard'] == 'yes'
Pb = df['marital'] == 'married'
(Pa & Pb).mean() / (Pa).mean()

np.float64(0.5456896551724137)

## Q9: If a customer has a management job, find the probability that he has a housing

In [126]:
Pa = df['job'] == 'management'
Pb = df.housing == 'yes'
(Pa & Pb).mean() / Pa.mean()

np.float64(0.5338577291381669)

<div style="font-size: 25px; color: red; text-align: center; font-weight: bold;"> 
Part 2: Bayes Theorem </div>

Kerala Flood Data

Data of monthly rainfall in Kerala from 1901 to 2018 is provided. It also contains information of floods.

Columns in Dataset:
- ```YEAR```: Year between 1901 to 2018
- ```JAN, FEB,..., DEC```:Rainfall in mm in the specified month
- ```ANNUAL RAINFALL```: Total rainfall in mm in that year
- ```FLOODS```: YES or NO, in that yea

In [127]:
df2 = pd.read_csv('kerala_floods.csv')
print(df2.shape)
df2.head()

(118, 16)

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [128]:
df2.isna().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

We need to use Bayes Therorm to calculate the probability of having a rainfall more than 500 mm in month
of June, provided it has flooded in that year ?

## 1- We may start by preparing the required columns:

- Create a new column named "June_more_than_500" and assign a value of 1 if the amount is more than 500 and 0 if it is less
than 500.
- Do the same for the 'FLOODS' column, assigning 1 for 'yes' and 0 for 'no'

In [129]:
df2['June_more_than_500'] = (df2['JUN'] > 500).astype(int)
df2['June_more_than_500'].head()

0    1
1    0
2    1
3    1
4    1
Name: June_more_than_500, dtype: int64

In [130]:
df2['FLOODS2'] = (df2['FLOODS'] == 'YES').astype(int)
df2['FLOODS2'].head()

0    1
1    1
2    1
3    1
4    0
Name: FLOODS2, dtype: int64

## 2- Select only the columns that will help to answer the main question.

In [142]:
df2[['June_more_than_500', 'FLOODS2']].head()

   June_more_than_500  FLOODS2
0                   1        1
1                   0        1
2                   1        1
3                   1        1
4                   1        0

## 3- Create a cross tabulation for 'FLOODS' and 'June_more_than_500'

In [132]:
pd.crosstab(df2['FLOODS2'], df2['June_more_than_500'], margins=True)

June_more_than_500   0   1  All
FLOODS2
0                   19  39   58
1                    6  54   60
All                 25  93  118

## 4- What is the probability of a rainfall more than 500mm in June?

In [133]:
p_rain = df2['June_more_than_500'].mean()
print(p_rain)

0.788135593220339

## 5- What is the probability of having a flood?

In [134]:
df2['FLOODS2'].mean()

np.float64(0.5084745762711864)

## 6- What is the probability of having a flood and a rainfall more than 500mm in June?

In [135]:
p_f_and_r = ((df2['FLOODS2'] == 1) & (df2['June_more_than_500'] == 1)).mean()
print(p_f_and_r)

0.4576271186440678

## 7- What is the Probability of having a flood given it rained more than 500mm in June?

In [136]:
p_flood_given_rain = p_f_and_r / p_rain
print(p_flood_given_rain)

0.5806451612903226

## 8- What is the probability of a rainfall less than 500mm in June?

In [137]:
p_not_rain = 1 - p_rain
print(p_not_rain)

0.211864406779661

## 9- What is probability of having a flood given that it rained less than 500mm?

In [138]:
p_flood_given_not_rain = ((df2['FLOODS2'] == 1) & (df2['June_more_than_500'] == 0)).mean() / p_not_rain
print(p_flood_given_not_rain)

0.24000000000000002

## Question: Calculate the probability of having a rainfall more than 500mm in month of June, provided it has flooded in that year ?

### 10- Answer this question by using Bayes Theorem and the law of the Total Probaility

p(B)= P(b|a)*p(a)+p(b|~a)*p(~a) flood total

In [145]:
p_flood_total = (p_flood_given_rain * p_rain) + (p_flood_given_not_rain * p_not_rain)
(p_flood_given_rain * p_rain) / p_flood_total

np.float64(0.8999999999999999)

### 11- Answer this question by using Bayes Theorem only.

p(a|b) = (p(b|a) * p(a)) / p(b)

In [140]:
p_a = (df2['JUN'] > 500).mean() 
p_b = (df2['FLOODS'] == 'YES').mean() 
p_b_given_a = (df2[df2['JUN'] > 500]['FLOODS'] == 'YES').mean()
(p_b_given_a * p_a) / p_b

np.float64(0.9000000000000001)